In [9]:
import torch
import numpy as np

# 张量创建
## 1 创建张量

In [10]:
tensor1 = torch.tensor(10.0)
print(tensor1)
print(tensor1.dtype)
print(tensor1.size())

tensor(10.)
torch.float32
torch.Size([])


In [12]:
tensor2 = torch.tensor(np.array([[1, 2, 3],[4, 5, 6]]))
print(tensor2)
print(tensor2.dtype)
print(tensor2.size())

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64
torch.Size([2, 3])


In [23]:
# 2 创建指定类型的张量
tensor1 = torch.Tensor(3,2,4)
print(tensor1)
print(tensor1.dtype)
print(tensor1.size())

tensor([[[2.9565e-11, 1.7839e-42, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])
torch.float32
torch.Size([3, 2, 4])


In [27]:
tensor2 = torch.Tensor(np.array([[1, 2, 3, 4],[4, 5, 6, 7]]))
print(tensor2)
print(tensor2.dtype)


tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]])
torch.float32


In [ ]:
# int(int32) 类型
tensor1 = torch.IntTensor(2,3)
tensor2 = torch.tensor([1,2,3],dtype=torch.int32)
print(tensor1.dtype)
print(tensor2.dtype)


torch.int32
torch.int32


In [30]:
# int(int64) 类型
tensor1 = torch.LongTensor(2,3)
tensor2 = torch.tensor([1,2,3],dtype=torch.int64)
print(tensor1.dtype)
print(tensor2.dtype)

torch.int64
torch.int64


In [31]:
# short (int16) 类型
tensor1 = torch.ShortTensor(2,3)
tensor2 = torch.tensor([1,2,3],dtype=torch.int16)
print(tensor1.dtype)
print(tensor2.dtype)

torch.int16
torch.int16


In [33]:
# int(int8) 类型
tensor1 = torch.ByteTensor(2,3)
tensor2 = torch.tensor([1,2,3],dtype=torch.uint8)
print(tensor1.dtype)
print(tensor2.dtype)

torch.uint8
torch.uint8


In [34]:
# float(float32) 类型
tensor1 = torch.FloatTensor(2,3)
tensor2 = torch.tensor([1,2,3],dtype=torch.float32)
print(tensor1.dtype)
print(tensor2.dtype)

torch.float32
torch.float32


In [35]:
# float(float64) 类型
tensor1 = torch.DoubleTensor(2,3)
tensor2 = torch.tensor([1,2,3],dtype=torch.float64)
print(tensor1.dtype)
print(tensor2.dtype)

torch.float64
torch.float64


In [36]:
# half(float16) 类型
tensor1 = torch.HalfTensor(2,3)
tensor2 = torch.tensor([1,2,3],dtype=torch.float16)
print(tensor1.dtype)
print(tensor2.dtype)


torch.float16
torch.float16


In [38]:
# bool 类型
tensor1 = torch.BoolTensor(2,3)
tensor2 = torch.tensor([1,2,3],dtype=torch.bool)
print(tensor1.dtype)
print(tensor2.dtype)
print(tensor1)
print(tensor2)

torch.bool
torch.bool
tensor([[False, False, False],
        [False, False, False]])
tensor([True, True, True])


In [ ]:
# 指定区间的张量创建
# 1 torch.arange() 函数
# 功能：返回一个1维张量，包含从start到end（不包含end）的以step为步长的序列
# 语法：torch.arange(start, end, step)
# 参数：
# start：序列的起始值，默认值为0
# end：序列的结束值（不包含在序列中）
# step：序列中每个元素之间的步长，默认值为1
# 返回值：1维张量
tensor1 = torch.arange(10,30,2)
print(tensor1)
tensor2 = torch.arange(6)
print(tensor2)


tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])
tensor([0, 1, 2, 3, 4, 5])


In [42]:
# 2 torch.linspace() 函数
# 功能：返回一个1维张量，包含从start到end（包含end）的num个等间隔的值
# 语法：torch.linspace(start, end, num)
# 参数：
# start：序列的起始值
# end：序列的结束值（包含在序列中）
# steps：序列中元素的数量，默认值为100
# 返回值：1维张量
tensor1 = torch.linspace(10,30,6)
print(tensor1)


tensor([10., 14., 18., 22., 26., 30.])


In [45]:
# 3 torch.logspace() 函数
# 功能：返回一个1维张量，包含从start到end（包含end）的num个等间隔的值，这些值是10的幂次

# 参数：
# start：序列的起始值，默认值为0
# end：序列的结束值（包含在序列中）
# steps：序列中元素的数量，默认值为100
# 返回值：1维张量
tensor1 = torch.logspace(1,3,3,base=2)
print(tensor1)


tensor([2., 4., 8.])


In [46]:
# 按数值
tensor1 = torch.zeros(2,3)
print(tensor1)
print(tensor1.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [47]:
tensor2 = torch.ones_like(tensor1)
print(tensor2)


tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [48]:
tensor1 = torch.full((2,3),6.5)
print(tensor1)
print(tensor1.dtype)

tensor([[6.5000, 6.5000, 6.5000],
        [6.5000, 6.5000, 6.5000]])
torch.float32


In [52]:
tensor2 = torch.empty_like(tensor1)
print(tensor2)
print(tensor2.dtype)

tensor([[2.3694e-38, 2.3694e-38, 2.3694e-38],
        [2.3694e-38, 2.3694e-38, 2.3694e-38]])
torch.float32


In [54]:
tensor1 = torch.eye(3,5)
print(tensor1)
print(tensor1.dtype)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])
torch.float32


In [57]:
# 随机张量创建
tensor1 = torch.rand(2,3)
print(tensor1)
print(tensor1.dtype)
tensor2 = torch.rand_like(tensor1)
print(tensor2)

tensor([[0.2327, 0.0799, 0.5034],
        [0.7172, 0.4514, 0.4510]])
torch.float32
tensor([[0.7920, 0.2971, 0.0744],
        [0.0410, 0.8360, 0.3390]])


In [59]:
tensor1 = torch.randint(low=0, high=100, size=(2,3))
print(tensor1)
tensor2 = torch.randint_like(tensor1, low=0, high=100)
print(tensor2)

tensor([[38, 49, 44],
        [75, 13, 65]])
tensor([[54, 20, 87],
        [13, 18, 84]])


In [61]:
# randn 随机生成标准正态分布（均值为0，标准差为1）的张量
tensor1 = torch.randn(4,3)
print(tensor1)
tensor2 = torch.randn_like(tensor1)
print(tensor2)

tensor([[-0.7323,  1.6715, -0.4921],
        [ 0.7118, -0.7269, -0.4282],
        [-0.1001,  2.9886,  0.4608],
        [-2.1586,  1.3201,  1.8486]])
tensor([[-2.4834,  1.6906, -0.4431],
        [-0.0794, -1.6410, -0.3792],
        [-0.5512, -0.2314,  1.2231],
        [ 0.8509, -0.8477, -0.3729]])


In [63]:
# torch.normal 随机生成正态分布（均值为mean，标准差为std）的张量
tensor1 = torch.normal(5,2 ,size=(2,3))
print(tensor1)
tensor2 = torch.normal(mean=5, std=2, size=tensor1.shape)
print(tensor2)


tensor([[ 4.5869, -0.7773,  5.2169],
        [ 2.6176,  4.4119,  5.0241]])
tensor([[ 4.7030,  4.4616,  3.6318],
        [-0.2508,  3.5693,  6.1514]])


In [68]:
# torch.randperm 随机生成一个从0到n-1的随机排列的张量
tensor1 = torch.randperm(10)
print(tensor1)

tensor([0, 9, 7, 2, 6, 3, 8, 5, 1, 4])


In [74]:
# 查看随机数生成器的初始种子
print(torch.random.initial_seed())

3632292072900


In [76]:
torch.random.manual_seed(42)

In [77]:
# 查看随机数生成器的初始种子
print(torch.random.initial_seed())

42
