In [1]:
import torch

In [2]:
# 1.四则运算
tensor1 = torch.randint(low=0, high=10, size=(2, 3))
print(tensor1)

tensor([[1, 4, 1],
        [3, 0, 3]])


In [3]:
print(tensor1+10)

tensor([[11, 14, 11],
        [13, 10, 13]])


In [4]:
print(tensor1.add(10))
print(tensor1)

tensor([[11, 14, 11],
        [13, 10, 13]])
tensor([[1, 4, 1],
        [3, 0, 3]])


In [5]:
print(tensor1.add_(10))
print(tensor1)


tensor([[11, 14, 11],
        [13, 10, 13]])
tensor([[11, 14, 11],
        [13, 10, 13]])


In [6]:
print(tensor1.sub_(10))
print(tensor1)


tensor([[1, 4, 1],
        [3, 0, 3]])
tensor([[1, 4, 1],
        [3, 0, 3]])


In [7]:
# 幂函数
print(tensor1.pow(2))
print(tensor1)


tensor([[ 1, 16,  1],
        [ 9,  0,  9]])
tensor([[1, 4, 1],
        [3, 0, 3]])


In [8]:
print(tensor1.pow_(2))
print(tensor1)

tensor([[ 1, 16,  1],
        [ 9,  0,  9]])
tensor([[ 1, 16,  1],
        [ 9,  0,  9]])


In [9]:
print(tensor1.sqrt())
print(tensor1)


tensor([[1., 4., 1.],
        [3., 0., 3.]])
tensor([[ 1, 16,  1],
        [ 9,  0,  9]])


In [10]:
tensor1 = tensor1.float()
print(tensor1.sqrt_())
print(tensor1)

tensor([[1., 4., 1.],
        [3., 0., 3.]])
tensor([[1., 4., 1.],
        [3., 0., 3.]])


In [11]:
tensor1 = torch.tensor([1.0,2,3])
print(tensor1)
print(2.7182818**tensor1)

tensor([1., 2., 3.])
tensor([ 2.7183,  7.3891, 20.0855])


In [12]:
print(tensor1)
print(tensor1.exp_())
print(tensor1)

tensor([1., 2., 3.])
tensor([ 2.7183,  7.3891, 20.0855])
tensor([ 2.7183,  7.3891, 20.0855])


In [13]:
# 计算张量的哈达玛积
tensor1 = torch.tensor(([1,2],[3,4]))
tensor2 = torch.tensor(([1,2],[3,4]))
print(tensor1 + tensor2)
print(tensor1 * tensor2)

tensor([[2, 4],
        [6, 8]])
tensor([[ 1,  4],
        [ 9, 16]])


In [14]:
print(tensor1.mul(tensor2))

tensor([[ 1,  4],
        [ 9, 16]])


In [15]:
# 张量的乘法
tensor1 = torch.tensor([[1,2,3],[4,5,6]])
tensor2 = torch.tensor([[1,2],[3,4],[5,6]])
print(tensor1 @ tensor2)
print(tensor1.matmul(tensor2))
print(tensor1.mm(tensor2))

tensor([[22, 28],
        [49, 64]])
tensor([[22, 28],
        [49, 64]])
tensor([[22, 28],
        [49, 64]])


In [16]:
tensor1 = torch.tensor([[[1,2,3],[4,5,6]],[[6,5,4],[3,2,1]]])
tensor2 = torch.tensor([[[1,2],[3,4],[5,6]],[[6,5],[4,3],[2,1]]])
print(tensor1 @ tensor2)
print(tensor1.matmul(tensor2))


tensor([[[22, 28],
         [49, 64]],

        [[64, 49],
         [28, 22]]])
tensor([[[22, 28],
         [49, 64]],

        [[64, 49],
         [28, 22]]])


In [17]:
# 严重内存的共享和节省内存
X = torch.randint(1,10,(3,2,4))
print(X)
print(id(X))

tensor([[[8, 3, 6, 2],
         [4, 1, 6, 2]],

        [[1, 1, 1, 4],
         [7, 5, 5, 8]],

        [[2, 3, 6, 5],
         [4, 9, 2, 1]]])
2434458258400


In [18]:
X += 10
print(X)
print(id(X))


tensor([[[18, 13, 16, 12],
         [14, 11, 16, 12]],

        [[11, 11, 11, 14],
         [17, 15, 15, 18]],

        [[12, 13, 16, 15],
         [14, 19, 12, 11]]])
2434458258400


In [19]:
X = torch.randint(1, 10,(3,2,4))
Y = torch.randint(1, 10,(3,4,1))
print(X.shape)
print(id(X))
X = X @ Y
print(X.shape)
print(id(X))


torch.Size([3, 2, 4])
2434458268960
torch.Size([3, 2, 1])
2434458268560
